apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://ecommerce-prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    type: loki
    url: http://ecommerce-loki:3100
    access: proxy
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceId":"(\w+)"'
          name: traceId
          url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://ecommerce-tempo:3200
    access: proxy
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: Loki
        filterBySpanID: false
        filterByTraceID: true
        mapTagNamesEnabled: false
        tags:
          - job
      tracesToMetrics:
        datasourceUid: Prometheus
        tags:
          - job
      serviceMap:
        datasourceUid: Prometheus
      nodeGraph:
        enabled: true